Upgrade to Debian 13 (Trixie) and S6 v3.2.2.0

diff --git a/base/rootfs/usr/local/sbin/run_services b/base/rootfs/usr/local/sbin/run_services
--- a/base/rootfs/usr/local/sbin/run_services
+++ b/base/rootfs/usr/local/sbin/run_services
@@ -1,9 +1,9 @@
 #!/bin/sh
 [ "$1" ] || exit 1
 for s in "$@"; do
-    if ! [ -d "/run/s6/services/$s/" ]; then
-        echo "ERROR: Missing service dir /run/s6/services/$s/" >&2
+    if ! [ -d "/run/service/$s/" ]; then
+        echo "ERROR: Missing service dir /run/service/$s/" >&2
         continue
     fi
-    s6-svc -o "/run/s6/services/$s"
+    s6-svc -o "/run/service/$s"
 done
